// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/db.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/login.tsx";
import * as $3 from "./routes/logout.tsx";
import * as $4 from "./routes/protected.tsx";
import * as $5 from "./routes/register.tsx";
import * as $$0 from "./islands/LoginForm.tsx";
import * as $$1 from "./islands/LogoutForm.tsx";
import * as $$2 from "./islands/Nav.tsx";

const manifest = {
  routes: {
    "./routes/db.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/login.tsx": $2,
    "./routes/logout.tsx": $3,
    "./routes/protected.tsx": $4,
    "./routes/register.tsx": $5,
  },
  islands: {
    "./islands/LoginForm.tsx": $$0,
    "./islands/LogoutForm.tsx": $$1,
    "./islands/Nav.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
